version: '3'

services:

  data:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    command: "true"

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

  # Adminer is not required but I find it helpful
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    restart: always
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    env_file:
      - .env

    depends_on:
      - db
    #    Checks that the DB is running before trying to start the web container
    #    https://stackoverflow.com/questions/35069027/docker-wait-for-postgresql-to-be-running
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python app.py'


volumes:
  db-data:
